export const surabayaDistricts = [
  "Asemrowo",
  "Benowo",
  "Bubutan",
  "Bulak",
  "Dukuh Pakis",
  "Gayungan",
  "Genteng",
  "Gubeng",
  "Gunung Anyar",
  "Jambangan",
  "Karang Pilang",
  "Kenjeran",
  "Krembangan",
  "Lakarsantri",
  "Mulyorejo",
  "Pabean Cantikan",
  "Pakal",
  "Rungkut",
  "Sambikerep",
  "Sawahan",
  "Semampir",
  "Simokerto",
  "Sukolilo",
  "Sukomanunggal",
  "Tambaksari",
  "Tandes",
  "Tegalsari",
  "Tenggilis Mejoyo",
  "Wiyung",
  "Wonocolo",
  "Wonokromo",
];
